/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119389-gd9bd8e9eb1-20250429"
#endif /* AVUTIL_FFVERSION_H */
